[package]
name = "io-vdir"
description = "Vdir client library for Rust"
version = "0.2.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.87"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["api-bindings", "filesystem", "no-std"]
keywords = ["io-free", "coroutine", "vdir", "vcard", "ical"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/io-vdir/latest/io_vdir"
repository = "https://github.com/pimalaya/io-vdir"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["client", "serde"]
client = ["dep:getrandom"]
serde = ["dep:serde"]

[[example]]
name = "std_store_item"
path = "examples/std_store_item.rs"
required-features = ["client"]

[dev-dependencies]
env_logger = "0.11"
tempfile = "3.20"

[dependencies]
getrandom = { version = "0.4", default-features = false, optional = true }
log = { version = "0.4", default-features = false }
serde = { version = "1", default-features = false, features = ["derive", "alloc"], optional = true }
thiserror = { version = "2", default-features = false }
