#[path = "create-collection.rs"]
pub mod create_collection;
#[path = "create-item.rs"]
pub mod create_item;
#[path = "delete-collection.rs"]
pub mod delete_collection;
#[path = "delete-item.rs"]
pub mod delete_item;
#[path = "list-collections.rs"]
pub mod list_collections;
#[path = "list-items.rs"]
pub mod list_items;
#[path = "read-item.rs"]
pub mod read_item;
#[path = "update-collection.rs"]
pub mod update_collection;
#[path = "update-item.rs"]
pub mod update_item;
